[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
reqwest-middleware = "0.4.0"
sqlx = "0.8.2"
tracing = "0.1.41"
warp = "0.3.7"
rust-argon2 = "2.1.0"
